/* 游戏数据 —— 改编自小说《天才俱乐部》(城城与蝉)
 * 全部为原创改编文案。L(中文, English) 双语对象由引擎 tr() 按语言解析。 */

const L = (z, e) => ({ z, e });

/* ── 时钟 ── */
const CLOCK = {
  total: 162,      // 22:00 → 00:42 共162分钟
  travel: 10,      // 地点间移动
  travelFast: 5,   // 有下水道近路(c14)后
};

/* ── 永久能力 ── */
const PERKS = {
  p_confident: L("胸有成竹 · 对话中多出关键选项", "Composure · extra key options in dialogue"),
  p_talk: L("谈判高手 · 说服类行动更省时", "Negotiator · persuasion costs less time"),
  p_resolve: L("提前入梦 · 每夜多出10分钟", "Early Sleeper · +10 minutes every night"),
  p_insight: L("知心话术 · 与CC相关的行动更省时", "Insight · CC-related actions cost less time"),
};

/* ── 情报(跨循环永久) ── */
const CLUES = {
  c01: { name: L("劫案的时刻", "Hour of the Heist"), cat: "人物",
    desc: L("戴卡通猫面具的男人——“大脸猫”——每晚23:00准时闯进中央银行。23:00之前,他都在蓝鸟酒吧里灌酒壮胆。",
      "The man in the cartoon-cat mask — “Bigface” — hits Central Bank at 23:00 sharp, every night. Before that, he drinks his courage up at the Bluebird Bar.") },
  c02: { name: L("金库的路线", "Route to the Vault"), cat: "杂项",
    desc: L("金库在地下二层。22:40警卫换班,侧门的监控有一段十来分钟的盲区,足够一个人溜进去。",
      "The vault is on basement level two. Guards change shift at 22:40, and the side-door cameras have a ten-minute blind spot — enough for one person to slip in.") },
  c03: { name: L("处决名单", "The Execution List"), cat: "人物",
    desc: L("大脸猫打算在得手前后,把自己的小弟一个一个全部干掉。理由五花八门,没有一个站得住脚。",
      "Bigface plans to execute his own crew one by one, before and after the job. His reasons vary. None of them hold up.") },
  c04: { name: L("大脸猫的女儿", "Bigface's Daughter"), cat: "人物",
    desc: L("他抢银行不是为了钱。他要那张传说中的“天才俱乐部”请柬——为女儿报仇。这是一个父亲最后的孤注一掷。",
      "He isn't robbing the bank for money. He wants the fabled Genius Club invitation — to avenge his daughter. A father's last desperate gamble.") },
  c05: { name: L("通风管道", "The Air Duct"), cat: "杂项",
    desc: L("金库天花板的通风管直通后巷天台。瘦小的人可以从那里无声地进出——那个蒙面女人CC,走的就是这条路。",
      "The duct in the vault ceiling leads to the back-alley rooftop. Someone slight can pass through in silence — that masked woman, CC, comes and goes this way.") },
  c06: { name: L("刻着你名字的保险箱", "The Safe With Your Name"), cat: "密码",
    desc: L("金库最深处,一只掉漆的旧保险箱上,端端正正刻着两个字:「林弦」。八位数字密码——你的生日,是错的。",
      "Deep in the vault sits an old, flaking safe engraved with a name: Lin Xian. Yours. Eight digits — and your birthday is wrong.") },
  c07: { name: L("没有年份的报纸", "The Paper With No Year"), cat: "真相",
    desc: L("梦里的报纸只印着“8月28日 星期五”。你把整份报纸翻烂了,也找不到一个年份。像是被人刻意抹掉了。",
      "The dream's newspaper reads only “Friday, August 28.” You've worn the pages thin — there is no year anywhere. As if someone erased it.") },
  c08: { name: L("断裂的历法", "The Broken Calendar"), cat: "真相",
    desc: L("旧书店的地方志把“智能手机的时代”称作“六百年前”。另外,店主随口抱怨:图书馆的后窗坏了半年,一直没人修。",
      "A local chronicle in the old bookstore calls the smartphone era “six hundred years ago.” Also: the shopkeep grumbles that the library's rear window has been broken for half a year.") },
  c09: { name: L("二六二四", "2624"), cat: "真相",
    desc: L("图书馆《城市编年史》的最后一页写着:今年,2624年。这个梦不是幻觉——它是六百年后的真实未来。",
      "The last page of the City Annals: this year is 2624. The dream is no hallucination — it is the real future, six hundred years from now.") },
  c10: { name: L("保险柜里的请柬", "The Invitation in the Vault"), cat: "人物",
    desc: L("大脸猫的真正目标:金库里藏着一张天才俱乐部的请柬。传闻只有最顶级的天才、富豪与大人物,才收得到它。",
      "Bigface's true target: hidden in the vault is a Genius Club invitation. They say only the greatest geniuses, tycoons and titans ever receive one.") },
  c11: { name: L("CC知道你的名字", "CC Knows Your Name"), cat: "人物",
    desc: L("她叫出了“林弦”两个字,却坚称你们从未见过。而她的枪口,每一次都会鬼使神差地偏出一寸。",
      "She spoke your name — Lin Xian — yet insists you've never met. And every single time, her muzzle drifts one inch wide.") },
  c12: { name: L("终末密码", "The Doomsday Code"), cat: "密码",
    desc: L("2624 · 0042——这个世界的年份,加上它每晚毁灭的时刻。八位数字。除此之外不可能是别的。",
      "2624 · 0042 — the year of this world, plus the minute it dies each night. Eight digits. It cannot be anything else.") },
  c13: { name: L("老张的烟瘾", "Old Zhang's Smoke Break"), cat: "杂项",
    desc: L("金库夜班警卫老张,每晚23:10准时溜去后巷抽烟。一根烟的工夫,地下二层形同虚设。",
      "Old Zhang, the vault's night guard, sneaks out for a smoke at 23:10 sharp. For one cigarette's length, basement two stands unguarded.") },
  c14: { name: L("下水道近路", "The Sewer Shortcut"), cat: "杂项",
    desc: L("广场后巷的下水道四通八达,贯通全城。虽然味道感人,但去哪儿都只要5分钟。",
      "The sewers behind the plaza run everywhere under the city. The smell is memorable — but any trip takes just 5 minutes.") },
  c15: { name: L("便利店的猫", "The Store Cat"), cat: "杂项",
    desc: L("便利店老板养的白猫,眼神灵得像会说话。寥寥几笔就能画出它的神态——你很想把它带回现实。",
      "The shopkeeper's white cat has eyes that all but talk. A few strokes could capture it — you itch to bring it back to reality.") },
  c16: { name: L("氧乙炔气割枪", "The Oxy-Acetylene Torch"), cat: "杂项",
    desc: L("现实里查到的:3000℃的切割焰能像切豆腐一样剖开旧保险箱。但两罐高压气体沉得要命——至少要五六个人手。",
      "Learned in reality: a 3000°C cutting flame opens an old safe like tofu. But the pressurized tanks are brutally heavy — you'd need five or six pairs of hands.") },
  c17: { name: L("被改写的名字", "The Rewritten Name"), cat: "真相",
    desc: L("你昨天在现实里给猫取名“莱茵”,今晚梦里的猫就改叫了“莱茵”。现实激起的涟漪,六百年后仍未平息。",
      "Yesterday, in reality, you named the cat “Rhein.” Tonight, the dream's cat answers to Rhein. Ripples from the present still spreading, six hundred years on.") },

  /* —— 第二章 —— */
  d01: { name: L("新东海市", "New Donghai City"), cat: "真相",
    desc: L("请柬背面浮着一行烫金小字:新东海市。城东那座“城中之城”,高墙环绕,门禁森严——你在梦里溜达了二十多年,从没进去过。",
      "Gilt letters surface on the invitation's back: New Donghai City. The walled city-within-a-city in the east — in twenty-odd years of dreaming, you've never once been inside.") },
  d02: { name: L("门禁的规矩", "Rules of the Gate"), cat: "杂项",
    desc: L("虹膜识别加请柬持有人双重验证。硬闯的人不会挨枪子——只会被几个白衣人无声无息地“请”出来,像捡走一片落叶。",
      "Iris scan plus invitation-holder verification. Gate-crashers don't get shot — men in white simply carry them out in silence, like picking up a fallen leaf.") },
  d03: { name: L("猫爸", "Bigface's Father"), cat: "人物",
    desc: L("大脸猫的父亲是个老数学家。算出“宇宙常数”后就疯了,满嘴胡话。随后,新东海市的人客客气气把他接去参加“学术论坛”——再无音讯。",
      "Bigface's father is an old mathematician. He solved the “universal constant” and went mad. Then people from New Donghai City politely escorted him to an “academic forum” — and he was never heard from again.") },
  d04: { name: L("满墙的42", "Walls of 42"), cat: "真相",
    desc: L("老宅的墙上,从地板到天花板,密密麻麻写满了同一个数字:42。宇宙常数,等于42。",
      "The old house's walls, floor to ceiling, are covered in one number, over and over: 42. The universal constant equals 42.") },
  d05: { name: L("消失的手稿", "The Vanished Manuscripts"), cat: "真相",
    desc: L("《宇宙常数导论》连同全部演算草稿一夜蒸发。屋里干净得反常——不像被拿走了,像被从世界上“抹除”了。",
      "An Introduction to the Universal Constant vanished overnight with every page of workings. The room is unnaturally clean — not taken. Erased from the world.") },
  d06: { name: L("同一种抹除", "The Same Erasure"), cat: "真相",
    desc: L("图书馆的馆藏记录里,那本书的条目也被删得干干净净。这手法你见过——“天才俱乐部”在历史上无痕,用的就是同一种抹除。",
      "The library's catalog entry for that book was scrubbed clean too. You know this technique — it's how the Genius Club left no trace in all of history.") },
  d07: { name: L("照片上的VV", "VV in the Photograph"), cat: "人物",
    desc: L("保险箱夹层里的老照片:长发、大胡子的中年男人,背面只写着两个字母——VV。他的侧脸,像极了你自己。",
      "An old photo from the safe's false bottom: a long-haired, bearded man. On the back, two letters — VV. His profile looks exactly like yours.") },
  d08: { name: L("内部人的密道", "The Insider's Passage"), cat: "杂项",
    desc: L("CC是新东海市的通缉客。她知道一条内部人才用的下水道密道,可以绕开门禁——她答应带你走一趟。",
      "CC is wanted inside New Donghai City. She knows an insiders' passage through the sewers that bypasses the gate — and she has agreed to take you through.") },
  d09: { name: L("今天的论坛", "Today's Forum"), cat: "杂项",
    desc: L("报纸头版:“新东海市学术论坛”,就在“今天”。也就是说——猫爸此时此刻,就在那座城里。",
      "Front page: the “New Donghai Academic Forum” is held “today.” Which means — the old man is inside that city, right now.") },
  d10: { name: L("顶层保险柜", "The Top-Floor Safe"), cat: "人物",
    desc: L("现实里,赵英珺把那张请柬锁进了X公司顶层的保险柜。她看请柬的眼神,平静得不像第一次见到它。",
      "In reality, Zhao Yingjun locked the invitation in the company's top-floor safe. The way she looked at it was far too calm for a first encounter.") },
};

/* ── 定时事件(at: 梦内分钟) ── */
const TIMED_EVENTS = [
  { at: 60,  flag: "heistStarted", warn: L("23:00 · 远处传来一声闷响——银行的方向。", "23:00 · A muffled bang in the distance — from the bank.") },
  { at: 90,  flag: "ccArrived" },
  { at: 150, warn: L("00:30 · 天边泛起不祥的白光……", "00:30 · An ominous white glow rises at the horizon…") },
];

/* ── 地点 ── */
const LOCATIONS = {
  home: {
    name: L("梦中公寓", "Dream Apartment"), icon: "🛏️",
    desc: L("每晚梦境开始的地方。窗外是那座你闭着眼都能画出来的城市。",
      "Where the dream begins each night. Outside the window: the city you could draw with your eyes closed."),
    actions: [
      { text: L("翻一翻手机", "Check your phone"), cost: 5, once: "phone",
        hide: (G) => G.meta.chapter >= 2 && hasClue("c07"), scene: "home_phone" },
      { text: L("站在窗前看城市", "Watch the city from the window"), cost: 5, once: "window", scene: "home_window" },
    ],
  },
  bank: {
    name: L("中央银行", "Central Bank"), icon: "🏦",
    desc: (G) => G.meta.chapter >= 2
      ? L("请柬已经到手,金库的故事翻篇了。营业大厅的灯,还是老样子亮着。",
          "The invitation is yours; the vault's story has turned its page. The lobby lights burn on as always.")
      : (G.run.flags.heistStarted
        ? L("卷帘门被撬开一半,里面隐约有手电的光柱晃动。劫案已经开始了。",
            "The shutter is pried half-open; flashlight beams sway inside. The heist has begun.")
        : L("营业大厅灯火通明。谁能想到一小时后,这里会被血洗。",
            "The lobby is brightly lit. Who'd guess that in an hour, it will run red.")),
    actions: [
      { text: L("以顾客身份踩点", "Scout as a customer"), cost: 10, when: [0, 55], req: ["c01"], once: "scouted",
        hide: (G) => G.meta.chapter >= 2,
        fresh: true, seenKey: "seen_scout", scene: "bank_scout" },
      { text: L("混进劫案,直奔金库", "Slip in with the heist, straight to the vault"), cost: 15, when: [55, 148], req: ["c01", "c02"], once: "vaulted",
        hide: (G) => G.meta.chapter >= 2,
        fresh: true, seenKey: "seen_vault", scene: "bank_vault" },
    ],
  },
  store: {
    name: L("便利店", "Convenience Store"), icon: "🏪",
    desc: L("二十四小时营业。老板永远在柜台后打同一局手机游戏。",
      "Open 24 hours. The owner is forever behind the counter, playing the same round of the same phone game."),
    actions: [
      { text: L("买一份报纸", "Buy a newspaper"), cost: 5, once: "paper", hide: (G) => G.meta.chapter >= 2, scene: "store_paper" },
      { text: L("再买一份今天的报纸", "Buy today's paper again"), cost: 5, once: "paper2", req: ["d03"],
        hide: (G) => G.meta.chapter < 2 || hasClue("d09"), fresh: true, seenKey: "seen_paper2",
        scene: "store_paper2" },
      { text: L("逗一逗老板的猫", "Play with the owner's cat"), cost: 5, once: "cat", scene: "store_cat" },
    ],
  },
  bookstore: {
    name: L("旧书店", "Old Bookstore"), icon: "📚",
    desc: L("天街尽头的旧书店,开到很晚。店主对每一本书的位置都了如指掌。",
      "The secondhand bookstore at the end of Skystreet, open late. The keeper knows the place of every single book."),
    actions: [
      { text: L("随便翻翻", "Browse the shelves"), cost: 10, once: "browse", scene: "book_browse" },
      { text: L("查证报纸的疑点", "Chase the newspaper's oddity"), cost: 15, req: ["c07"], once: "history",
        hide: (G) => G.meta.chapter >= 2 && hasClue("c08"),
        fresh: true, seenKey: "seen_history", scene: "book_history" },
    ],
  },
  library: {
    name: L("市立图书馆", "City Library"), icon: "🏛️",
    desc: L("夜间闭馆。铁门锁得死死的,门口保安亭还亮着灯。",
      "Closed at night. The iron gate is locked tight; the guard booth light is still on."),
    actions: [
      { text: L("敲敲正门", "Knock on the front door"), cost: 5, once: "door", scene: "lib_door" },
      { text: L("从坏掉的后窗潜入", "Slip in through the broken rear window"), cost: 15, req: ["c08"], once: "sneak",
        hide: (G) => G.meta.chapter >= 2 && hasClue("c09"), scene: "lib_truth" },
      { text: L("从坏掉的后窗潜入", "Slip in through the broken rear window"), cost: 15, req: ["c17"], once: "sneak",
        hide: (G) => hasClue("c08") || (G.meta.chapter >= 2 && hasClue("c09")), scene: "lib_truth" },
      { text: L("查《宇宙常数导论》的馆藏记录", "Search the catalog for the Constant book"), cost: 15, req: ["d04"], once: "constant",
        hide: (G) => G.meta.chapter < 2 || hasClue("d06"),
        fresh: true, seenKey: "seen_constant", scene: "lib_constant" },
    ],
  },
  bar: {
    name: L("蓝鸟酒吧", "Bluebird Bar"), icon: "🍺",
    desc: L("烟雾和劣质威士忌的味道。最里面的卡座,坐着几个压低帽檐的男人。",
      "Smoke and cheap whiskey. In the back booth sit several men with their caps pulled low."),
    actions: [
      { text: L("在邻座偷听", "Eavesdrop from the next booth"), cost: 10, when: [0, 55], once: "listen",
        hide: (G) => G.meta.chapter >= 2 && hasClue("c03"), scene: "bar_listen" },
      { text: L("凑过去和大脸猫搭话", "Sit down across from Bigface"), cost: 10, when: [0, 55], req: ["c03"], once: "talked",
        hide: (G) => G.meta.chapter >= 2 && hasClue("c04"),
        fresh: true, seenKey: "seen_talk", scene: "bar_talk" },
      { text: L("说服他:团结就是力量", "Convince him: strength in numbers"), cost: (G) => hasPerk("p_talk") ? 10 : 15,
        when: [0, 55], req: ["c04", "c16"], once: "persuaded",
        fresh: true, seenKey: "seen_persuade", scene: "bar_persuade" },
      { text: L("问起他的父亲", "Ask about his father"), cost: 10, when: [0, 55], req: ["c04"], once: "askedDad",
        hide: (G) => G.meta.chapter < 2 || hasClue("d03"),
        fresh: true, seenKey: "seen_dad", scene: "bar_father" },
    ],
  },
  rooftop: {
    name: L("后巷 · 天台", "Back Alley · Rooftop"), icon: "🌃",
    desc: L("锈蚀的消防梯一路通向天台。风很大,能望见银行的后墙和一个方形的通风口。",
      "A rusted fire escape climbs to the rooftop. The wind is fierce; you can see the bank's rear wall and a square air vent."),
    actions: [
      { text: L("在通风口旁守株待兔", "Wait in ambush by the vent"), cost: 10, when: [80, 148], req: ["c05"], once: "ccMet",
        hide: (G) => G.meta.chapter >= 2 && hasClue("d08"),
        fresh: true, seenKey: "seen_cc", scene: "cc_talk" },
      { text: L("对她说出照片上的名字", "Say the name from the photograph"), cost: (G) => hasPerk("p_insight") ? 5 : 10,
        when: [80, 148], req: ["d07"], once: "ccMet",
        hide: (G) => G.meta.chapter < 2 || hasClue("d08"),
        fresh: true, seenKey: "seen_vv", scene: "cc_vv" },
    ],
  },
  /* —— 第二章新地点 —— */
  newcity: {
    name: L("新东海市 · 关卡", "New Donghai · Checkpoint"), icon: "🏙️",
    hide: (G) => G.meta.chapter < 2,
    desc: L("高墙在夜色里泛着冷光,墙内的天际线比外面高出一整个时代。哨卡的白衣人一动不动,像一排雕塑。",
      "The wall gleams cold in the night; the skyline within stands a whole era taller. The men in white at the gate never move — a row of statues."),
    actions: [
      { text: L("远远观察门禁", "Observe the gate from afar"), cost: 10, once: "watched", hide: (G) => hasClue("d02"),
        fresh: true, seenKey: "seen_gate", scene: "gate_watch" },
      { text: L("硬闯试试", "Try to force your way in"), cost: 10, scene: "gate_force" },
      { text: L("走密道潜入(CC带路)", "Take the hidden passage (CC leads)"), cost: 25, req: ["d08", "d09"], once: "sneaked",
        fresh: true, seenKey: "seen_sneak", scene: "sneak" },
    ],
  },
  oldhouse: {
    name: L("大脸猫老宅", "Bigface's Old House"), icon: "🏚️",
    hide: (G) => G.meta.chapter < 2 || !hasClue("d03"),
    desc: L("城郊的老房子,院门虚掩。信箱里塞满没人取的传单,门牌被雨水泡得发白。",
      "An old house on the city's edge, its gate ajar. The mailbox overflows with unclaimed flyers; rain has bleached the number plate white."),
    actions: [
      { text: L("推门进屋", "Push the door open"), cost: 10, once: "entered", hide: (G) => hasClue("d04"),
        fresh: true, seenKey: "seen_house", scene: "house_42" },
      { text: L("翻找书桌", "Search the desk"), cost: 10, req: ["d04"], once: "desked", hide: (G) => hasClue("d05"),
        scene: "house_desk" },
    ],
  },
  plaza: {
    name: L("城市广场 · 钟楼", "City Plaza · Clock Tower"), icon: "🕐",
    desc: L("巨大的钟楼俯瞰全城。指针一格一格,走向那个你熟悉的时刻。",
      "The great clock tower overlooks the city. Tick by tick, the hands crawl toward the minute you know too well."),
    actions: [
      { text: L("仰望钟楼", "Look up at the clock"), cost: 5, once: "clock", scene: "plaza_clock" },
      { text: L("钻进后巷下水道", "Climb into the back-alley sewer"), cost: 10, once: "sewer", scene: "plaza_sewer" },
      { text: L("在观景台等到最后一刻", "Wait on the deck until the very end"), cost: 5, once: "doom", scene: "plaza_doom" },
    ],
  },
};

/* ── 场景 ── */
const SCENES = {

  /* ═══ 首夜(教学) ═══ */
  intro: [
    { art: "🌙" },
    { t: L("又是这个梦。第 8395 次,大概。\n同一座城市,同一天,同样会在 00:42 毁灭——从你出生起,每晚如此。",
        "This dream again. The 8,395th time, give or take.\nSame city, same day, same annihilation at 00:42 — every night since the day you were born.") },
    { t: L("梦里的一切第二天都会复原。只有你的记忆,能带出去。\n所以你早就不把它当噩梦了。这里是你的游乐场。",
        "Everything here resets by the next night. Only your memory leaves with you.\nSo you stopped calling it a nightmare long ago. This place is your playground.") },
    { art: "🐱" },
    { who: L("卡通猫面具男", "Man in a Cat Mask"), t: L("哟,密码专家!可算找着你了。我小弟把银行的门都撬好了,就等你了!",
        "Hey, the code expert! Finally. My boys already jimmied the bank door — we've been waiting on you!") },
    { t: L("一个满脸横肉的男人搂住你的肩膀。面具是只二次元猫,道上人称——大脸猫。\n今晚你心血来潮想换个剧本,就顺着他之前认错人的话头应了下来。",
        "A heavyset man throws an arm around your shoulder. The mask is a cartoon cat; the street calls him Bigface.\nTonight you feel like a different script, so you play along with his mistaken identity.") },
    { art: "🏦" },
    { t: L("银行后门。放风的小弟刚比出OK的手势——\n嘭!!大脸猫一枪把他放倒了。",
        "The bank's back door. The lookout flashes an OK sign —\nBANG!! Bigface drops him with one shot.") },
    { who: L("大脸猫", "Bigface"), t: L("这人手脚不干净,留不得!少个人分钱,你该高兴啊老弟!",
        "That one had sticky fingers. Couldn't keep him! One less cut of the money — you should be happy, kid!") },
    { t: L("往里走,配电箱前的小弟刚剪断警报线——嘭!!又是一枪。\n“这个嘛,他勾引你嫂子。”大脸猫解释得理直气壮。",
        "Further in, another crew member snips the alarm wire — BANG!! Another shot.\n“That one? He flirted with your sister-in-law.” Bigface explains it like a righteous man.") },
    { t: L("他从腰后掏出一坨胶布缠着的灰色物体塞给你:“C4。你要是觉得哥想黑吃黑,就按下开关跟哥同归于尽。这下放心了吧?”\n……这大哥的脑回路,还挺坦荡。",
        "He pulls a tape-wrapped gray lump from his belt and shoves it at you. “C4. If you ever think I'm double-crossing you, hit the switch and take us both out. Feel safe now?”\n…You have to admire the honesty of his logic.") },
    { art: "🚪" },
    { t: L("地下二层。一道厚重的银色密码门挡在面前。\n大脸猫指指手表:“抓紧!主电力一恢复,警报就响!”",
        "Basement two. A massive silver coded door blocks the way.\nBigface taps his watch: “Hurry! The second main power's back, the alarms go off!”") },
    { menu: [
      { text: L("把C4贴在门上,倒数十秒", "Slap the C4 on the door, count down ten"), goto: "boom" },
      { text: L("老老实实输一个密码试试", "Actually try a passcode"), goto: "crack" },
    ]},

    { label: "boom" },
    { t: L("“10。”你说。\n“10分钟!?太久了吧!”\n“9……8……7……”",
        "“Ten,” you say.\n“Ten MINUTES!? Way too long!”\n“Nine… eight… seven…”") },
    { t: L("你把C4拍在门上撒腿就跑。身后传来大脸猫撕心裂肺的一声“Shift——!”",
        "You slap the C4 onto the door and bolt. Behind you, Bigface lets out a soul-rending “Shift——!!”") },
    { grant: "c01" },
    { t: L("轰!!!!!\n气浪掀飞了半面墙。在意识涣散前,你听见警报声、警笛声——\n还有一个女人隔着硝烟的怒骂。",
        "BOOM!!!!!\nThe blast takes out half the wall. As your mind scatters you hear alarms, sirens —\nand a woman cursing through the smoke.") },
    { die: L("数不清的砖块砸在身上。", "Countless bricks come down on you.") },

    { label: "crack" },
    { t: L("你在键盘上敲下自己的生日。\n——嘀。红灯。\n再试一遍。还是红灯。",
        "You key in your own birthday.\n— Beep. Red light.\nAgain. Red light.") },
    { grant: "c01" },
    { t: L("咔。清脆的电流声——主电路恢复了。\n呜哇!呜哇!警报炸响。大脸猫的脸比面具还扭曲。",
        "Click. A crisp electric hum — main power is back.\nWEE-OO! WEE-OO! The alarms detonate. Bigface's face twists worse than his mask.") },
    { art: "🎭" },
    { t: L("黑暗里走出一个戴白色面具的蒙面女人,手枪稳稳指着你们。\n嘭。大脸猫连一句遗言都没来得及说。",
        "Out of the dark steps a masked woman in white, pistol rock-steady on you both.\nBang. Bigface doesn't even get his last words out.") },
    { who: "CC", t: L("……林弦?", "…Lin Xian?") },
    { t: L("她居然叫出了你的名字。枪口对着你,却迟迟没有扣下。\n就在这时,破门锤砸开了金库外门——特警攻入,枪声大作。",
        "She knows your name. Her muzzle is on you, but her finger won't close.\nThen a ram smashes the vault's outer door — SWAT pours in, gunfire everywhere.") },
    { die: L("视野的最后,是她转身钻进通风管的背影。", "The last thing you see is her back, vanishing into the air duct.") },
  ],

  /* ═══ 每夜开场 ═══ */
  night_open: [
    { art: "🌙" },
    { t: (G) => L(
        "熟悉的天花板,熟悉的" + (hasPerk("p_resolve") ? "21:50" : "22:00") + "。\n第 " + (G.meta.loop + 1) + " 夜。世界毫无破绽地复原了——除了你口袋里越来越厚的“记忆”。",
        "The familiar ceiling, the familiar " + (hasPerk("p_resolve") ? "21:50" : "22:00") + ".\nNight " + (G.meta.loop + 1) + ". The world has reset without a single seam — except for the ever-thickening “memory” in your pocket.") },
    { cond: (G) => G.meta.butterfly.cat && !G.meta.ms.sawBfly,
      t: L("……等等。昨天在现实里,你刚给那只猫的画像取了名字。\n如果这个梦真的和现实有关——便利店那只猫,今晚会不会不一样?",
        "…Wait. Yesterday, in reality, you named that cat in your sketch.\nIf this dream truly touches reality — will the store cat be different tonight?") },
    { back: true },
  ],

  /* ═══ 公寓 ═══ */
  home_phone: [
    { art: "📱" },
    { t: L("梦里你的手机永远是满电。锁屏上写着:8月28日,星期五。",
        "In the dream your phone is always fully charged. The lock screen reads: Friday, August 28.") },
    { t: L("你以前从没在意过——今天却越看越不对劲。\n日历翻到头,也只有月和日。年份呢?这部手机,不显示年份。",
        "You never gave it a thought — but tonight it looks wrong.\nYou scroll the calendar to its end: only months and days. Where is the year? This phone shows no year.") },
    { grant: "c07" },
    { back: true },
  ],
  home_window: [
    { art: "🌆" },
    { t: L("城市的灯火一如既往。广场的钟楼刺破天际线,像一根巨大的表针。",
        "The city lights are as they always are. The plaza's clock tower pierces the skyline like an enormous watch hand.") },
    { t: L("00:42的时候,站在那上面,应该能看到“世界毁灭”的全景吧。\n……你居然从来没试过。",
        "At 00:42, from up there, you could probably watch the whole world end in panorama.\n…Strange, you've never once tried.") },
    { back: true },
  ],

  /* ═══ 银行 ═══ */
  bank_scout: [
    { art: "🏦" },
    { t: L("你揣着手在大厅里溜达,像一个纠结要不要办卡的普通客户。",
        "Hands in pockets, you stroll the lobby like a customer agonizing over a new card.") },
    { t: L("半小时后,你摸清了:金库在地下二层;22:40警卫换班;侧门的监控,有一段十来分钟的盲区。\n只要卡准时间,一个人也能溜进去。",
        "Half an hour later you have it: vault on basement two; shift change at 22:40; the side-door cameras blind for a good ten minutes.\nTime it right, and one person could slip through alone.") },
    { grant: "c02" },
    { menu: [
      { text: L("再多盯一会儿那个夜班警卫(-5分)", "Watch the night guard a while longer (-5 min)"), cost: 5, goto: "guard" },
      { text: L("见好就收", "Quit while you're ahead"), back: true },
    ]},
    { label: "guard" },
    { t: L("夜班警卫的工牌写着“张”。他隔一会儿就摸一下胸口的烟盒,坐立难安。\n23:10,他准时溜向后巷——一根烟的工夫,地下二层没人看守。",
        "The night guard's badge reads “Zhang.” Every few minutes he pats the cigarette pack at his chest, restless.\nAt 23:10 sharp he slips toward the back alley — for one cigarette, basement two goes unwatched.") },
    { grant: "c13" },
    { back: true },
  ],

  bank_vault: [
    { art: "🏦" },
    { cond: (G) => G.run.flags.heistStarted,
      t: L("劫案的枪声就是最好的掩护。你贴着墙根,从侧门的监控盲区滑进去,直下地下二层。",
        "The heist's gunfire is the best cover there is. You hug the wall, slide through the side door's blind spot, straight down to basement two.") },
    { cond: (G) => !G.run.flags.heistStarted,
      t: L("换班的间隙,你从侧门的监控盲区溜进去,直下地下二层。走廊里安静得能听见自己的心跳。",
        "In the gap between shifts you slip through the camera blind spot and head down to basement two. The corridor is so quiet you can hear your own heartbeat.") },
    { cond: (G) => hasClue("c13"),
      t: L("路过警卫室时,老张的座位果然空着——烟瘾比闹钟还准。",
        "Passing the guard room: Old Zhang's chair is empty, as promised. His habit keeps better time than any clock.") },
    { art: "🗄️" },
    { t: L("金库里立着一整面墙的保险柜。而在最深处的角落,那只掉漆的旧保险箱上,刻着两个字:\n「林弦」。",
        "The vault holds a whole wall of safes. And in the deepest corner, engraved on an old flaking one, a name:\nLin Xian.") },
    { grant: "c06" },
    { cond: (G) => G.run.flags.ccArrived, goto: "cc_here" },
    { t: L("头顶的通风口传来窸窣声——你闪身躲进柜子的阴影。\n一个瘦小的身影从管道里无声落地:白色面具,蒙面女人。她也是冲着保险柜来的。",
        "A rustle from the vent overhead — you melt into the shadow of the cabinets.\nA slight figure drops soundlessly from the duct: white mask, a woman. She's here for the safe too.") },
    { grant: "c05" },
    { goto: "safe" },

    { label: "cc_here" },
    { t: L("保险柜前已经站了一个人:白色面具,蒙面女人。头顶的通风口还在晃——她是从管道里下来的。",
        "Someone is already at the safe: white mask, a woman. The vent overhead still sways — she came down through the duct.") },
    { grant: "c05" },
    { who: "CC", t: L("……又是你。别碍事。", "…You again. Stay out of my way.") },
    { t: L("她说“又”。可这是你今晚第一次见她。\n她的枪口对着你,却又一次,偏出了一寸。",
        "She said “again.” But this is the first time you've met her tonight.\nHer muzzle is on you — and once more, it drifts an inch wide.") },

    { label: "safe" },
    { menu: [
        { text: L("输入你的生日(-5分)", "Enter your birthday (-5 min)"), cost: 5, goto: "fail" },
        { text: L("推理密码", "Deduce the code"), req: ["c09", "c11"], goto: "deduce" },
        { text: L("输入 2624 0042", "Enter 2624 0042"), req: ["c12"], goto: "open" },
        { text: L("按计划:上气割枪", "Follow the plan: bring up the torch"), req: ["c16"],
          hide: (G) => !(G.run.flags.gangAlly && (G.meta.ms.ccTalks || 0) >= 3),
          goto: "coop" },
        { text: L("不管保险箱了,搬钱躺平", "Forget the safe — grab cash and coast"), hide: (G) => !hasClue("c09"),
          set: (G) => { G.meta.ms.slacker = true; SAVE.save(G.meta); }, goto: "slack" },
        { text: L("撤退", "Withdraw"), back: true },
      ],
      prompt: L("八位数字密码。保险箱冰冷地等着你。", "Eight digits. The safe waits, cold as ever.") },

    { label: "fail" },
    { t: L("嘀。红灯。\n八位数,你试过生日、倒序、乱序……全都是红灯。如果这箱子真是“你的”,密码为什么不是你的生日?",
        "Beep. Red light.\nEight digits — you've tried your birthday forward, backward, scrambled… all red. If this safe is truly “yours,” why isn't the code your birthday?") },
    { goto: "safe" },

    { label: "deduce" },
    { t: L("你盯着那行刻字,把所有已知的碎片摆在一起:\n这个世界的年份——2624。它每晚毁灭的时刻——00:42。",
        "You stare at the engraving and lay every known fragment side by side:\nThe year of this world — 2624. The minute it dies each night — 00:42.") },
    { t: L("一个属于这个梦本身的数字。八位。\n除此之外,不可能是别的。",
        "A number belonging to the dream itself. Eight digits.\nIt cannot be anything else.") },
    { grant: "c12" },
    { goto: "safe" },

    { label: "open" },
    { art: "✉️" },
    { t: L("2、6、2、4、0、0、4、2。\n——咔哒。\n绿灯。箱门弹开的瞬间,你听见了自己的心跳。",
        "2, 6, 2, 4, 0, 0, 4, 2.\n— Click.\nGreen light. The instant the door springs open, you hear your own heart.") },
    { t: L("箱子里没有钱,没有金条。\n只有一张暗红色的卡片,烫金的四个字:天才俱乐部。",
        "No money inside. No gold.\nOnly a dark red card, four gilt characters: The Genius Club.") },
    { t: L("身后传来面具下一声几不可闻的叹息。\n“你到底……是什么人。”",
        "Behind you, the faintest sigh escapes the mask.\n“What… are you, exactly?”") },
    { set: (G) => { G.meta.ms.invite = true; SAVE.save(G.meta); } },
    { t: L("请柬带不回现实。但上面的每一个字、每一道纹路,你都刻进了脑子里。\n你靠着保险柜坐下,静静等待00:42。",
        "The invitation can't cross into reality. But every character, every embossed line, is carved into your mind.\nYou sit down against the safe and quietly wait for 00:42.") },
    { end: (G) => window.__midnight() },

    { label: "coop" },
    { art: "🔥" },
    { t: L("23:40,通风管垂下绳索。CC、大脸猫,还有三个“今晚没有被处决”的小弟,把两只钢瓶一寸一寸吊进金库。",
        "23:40. Ropes drop from the air duct. CC, Bigface, and three crew members who were not executed tonight lower two steel tanks into the vault, inch by inch.") },
    { t: L("点火。3000℃的白炽火焰贴上箱体,钢板像黄油一样卷开,火花溅了一地。\n大脸猫盯着切开的缺口,呼吸都停了。",
        "Ignition. The 3000°C white flame kisses the steel; the plate curls open like butter, sparks sheeting to the floor.\nBigface stares at the widening cut and forgets to breathe.") },
    { t: L("暗红色的卡片躺在里面。烫金的四个字:天才俱乐部。\n这个满手血腥的男人,隔着面具哭出了声——为了他的女儿。",
        "The dark red card lies within. Four gilt characters: The Genius Club.\nThe man with blood on his hands weeps aloud behind his mask — for his daughter.") },
    { who: "CC", t: L("……原来一个人是打不开的。这么多年,我居然没想过“人手”这个答案。",
        "…So it never could be opened alone. All these years, and “more hands” was the answer I never once considered.") },
    { set: (G) => { G.meta.ms.coopOpen = true; G.meta.ms.invite = true; SAVE.save(G.meta); } },
    { t: L("远处,天边泛起白光。你们六个人并排坐在金库里,分食一包小弟买来的烟。\n等待00:42,像等待一场散场的电影。",
        "Far off, white light rises at the horizon. The six of you sit in a row in the vault, sharing a pack of cigarettes.\nWaiting for 00:42, like waiting out the credits of a film.") },
    { end: (G) => window.__midnight() },

    { label: "slack" },
    { art: "💰" },
    { t: L("你把成捆的钞票往包里塞,塞满了就往地上撒,撒累了就躺在钱堆里。\n反正带不回去。反正明晚还有。",
        "You stuff bundles of cash into a bag; when it's full you throw the rest in the air, and when you're tired you lie down in the pile.\nNone of it comes home anyway. There'll be more tomorrow night anyway.") },
    { t: L("既然已经知道这个梦是什么,那答案还重要吗?\n躺平,也是一种选择……吧。",
        "Now that you know what this dream is — do the answers even matter?\nCoasting is a choice too… right?") },
    { back: true },
  ],

  /* ═══ 便利店 ═══ */
  store_paper: [
    { art: "📰" },
    { t: L("你抽出一份当天的报纸。头版在讲“冬眠舱保费新政”,你从小看到大,早没兴趣了。",
        "You pull out today's paper. The front page covers “new hibernation-pod premium policy” — you've read it since childhood; it bores you now.") },
    { t: L("但今天,你盯住了报头的日期:\n“8月28日 星期五”。\n……年份呢?你把整份报纸翻烂了,一个年份都没有。",
        "But today your eyes catch on the dateline:\n“Friday, August 28.”\n…Where's the year? You wear the pages thin — there is no year anywhere.") },
    { grant: "c07" },
    { back: true },
  ],
  store_paper2: [
    { art: "📰" },
    { t: L("还是那份没有年份的报纸。但这一次,你的目光钉在了头版:\n「新东海市学术论坛今日启幕 顶尖学者齐聚」。",
        "The same yearless paper. But this time your gaze nails to the front page:\n“New Donghai Academic Forum Opens Today — Top Scholars Convene.”") },
    { t: L("今日。\n这个梦永远重复着同一天——也就是说,每一夜,猫爸都在那座城里,被“论坛”着。\n他就在墙的那一边。",
        "Today.\nThe dream repeats one single day forever — meaning every night, the old man is inside that city, being “forumed.”\nHe is just beyond the wall.") },
    { grant: "d09" },
    { back: true },
  ],
  store_cat: [
    { art: "🐈" },
    { cond: (G) => !G.meta.butterfly.cat, goto: "cat_a" },
    { t: L("白猫蹲在收银台上,尾巴一甩一甩。\n“它叫什么?”你状似随意地问。",
        "The white cat perches on the register, tail flicking.\n“What's her name?” you ask, as casually as you can manage.") },
    { who: L("便利店老板", "Shopkeeper"), t: L("莱茵。怎么了?", "Rhein. Why?") },
    { set: (G) => { G.meta.ms.sawBfly = true; SAVE.save(G.meta); } },
    { t: L("你的汗毛瞬间立了起来。\n昨天。就在昨天的现实里,是你亲手把那幅猫的画像命名为“莱茵”。\n而这个“六百年后”的梦,一夜之间,跟着变了。",
        "Every hair on your body stands up.\nYesterday. Just yesterday, in reality, you yourself named that cat sketch “Rhein.”\nAnd this dream — six hundred years downstream — changed overnight to match.") },
    { grant: "c17" },
    { grant: "c15" },
    { back: true },

    { label: "cat_a" },
    { t: L("白猫蹲在收银台上,尾巴一甩一甩,神态灵得像会说话。\n“它叫珂珂。”老板头也不抬。",
        "The white cat perches on the register, tail flicking, its expression practically verbal.\n“Her name's Keke,” the owner says without looking up.") },
    { t: L("你多看了两眼,忽然生出一个念头:这么可爱的猫,寥寥几笔就能画下来。\n要是能把它“带回”现实……",
        "You watch a moment longer and a thought sparks: a cat this charming could be captured in a few strokes.\nIf only you could “carry” her back to reality…") },
    { grant: "c15" },
    { back: true },
  ],

  /* ═══ 旧书店 ═══ */
  book_browse: [
    { art: "📚" },
    { t: L("店主眼皮都没抬。你在书架间穿行,指尖扫过一排排书脊。",
        "The keeper doesn't so much as lift an eyelid. You drift between shelves, fingertips brushing spine after spine.") },
    { t: L("科技类的书名一水儿的陌生:《冬眠舱通识》《轨道电梯五十年》……\n历史区反倒厚厚一堆。这家店,历史书多得反常。",
        "The tech titles are uniformly alien: A Primer on Hibernation Pods, Fifty Years of the Orbital Elevator…\nThe history section, by contrast, is heaped high. This store has an unnatural appetite for history.") },
    { back: true },
  ],
  book_history: [
    { art: "📖" },
    { t: L("“我想查一件……很久以前的事。”你把报纸的疑惑压在舌根,换了个问法。",
        "“I'm looking into something… very old.” You keep the newspaper riddle under your tongue and phrase it differently.") },
    { t: L("店主慢悠悠推来一册地方志。你翻到民俗篇,一行字让你如坠冰窟:\n“……此习俗可上溯六百年前,即智能手机初代普及之时代。”",
        "The keeper slides over a local chronicle. You flip to the folklore section, and one line drops you into ice water:\n“…this custom dates back six hundred years, to the era when the first smartphones spread.”") },
    { t: L("智能手机。六百年前。\n你合上书,指尖发凉。店主还在絮叨:“要查更早的,去图书馆。哦对,它后窗坏半年了都没人修,白天去,别翻窗啊。”",
        "Smartphones. Six hundred years ago.\nYou close the book, fingertips gone cold. The keeper rambles on: “For anything older, try the library. Oh — their rear window's been broken half a year, nobody's fixed it. Go in the daytime. Don't climb in.”") },
    { grant: "c08" },
    { back: true },
  ],

  /* ═══ 图书馆 ═══ */
  lib_door: [
    { art: "🏛️" },
    { t: L("你敲了敲铁门。保安亭里探出一个脑袋:“闭馆了!白天再来!”\n问题是——你的梦里,永远没有白天。",
        "You rap on the iron gate. A head pokes from the guard booth: “We're closed! Come back in the daytime!”\nThe problem is — your dream has no daytime. Ever.") },
    { back: true },
  ],
  lib_truth: [
    { art: "🏛️" },
    { t: L("后窗果然虚掩着,窗框上的锁锈成了一坨。你翻进去,打开手机照明。",
        "The rear window is indeed ajar, its lock rusted into a lump. You climb through and switch on your phone light.") },
    { t: L("编年史区。你抽出最新的一册《城市编年史》,直接翻到最后一页——",
        "The annals section. You pull the newest volume of the City Annals and flip straight to the last page —") },
    { art: "🕮" },
    { t: L("“本卷修至今年:2624年。”", "“This volume is current to the present year: 2624.”") },
    { t: L("2624。\n不是幻觉,不是脑补,白纸黑字。\n你做了二十多年的这个梦——是六百年后的、真实的未来。",
        "2624.\nNot a hallucination. Not your imagination. Black ink on white paper.\nThe dream you've dreamed for twenty-odd years — is the real future, six hundred years from now.") },
    { grant: "c09" },
    { t: L("书页在你手里微微发抖。\n那么保险箱上的“林弦”……那么CC……那么“天才俱乐部”……全都是真的。",
        "The pages tremble in your hands.\nThen the “Lin Xian” on the safe… then CC… then the “Genius Club”… all of it is real.") },
    { back: true },
  ],
  lib_constant: [
    { art: "🏛️" },
    { t: L("馆藏检索机。你敲下书名:《宇宙常数导论》。\n——无结果。\n换作者名。无结果。换关键词“宇宙常数”。相关条目:0。",
        "The catalog terminal. You type the title: An Introduction to the Universal Constant.\n— No results.\nAuthor's name. Nothing. Keyword “universal constant.” Related entries: 0.") },
    { t: L("你调出借阅日志的底层记录,在连续的流水号里,发现了一段整整齐齐的空缺——号码还在,内容没了。\n像一排牙齿里被拔掉的那颗,创口平整得吓人。",
        "You pull the raw circulation logs. In an unbroken run of serial numbers sits a neat, clean gap — the numbers remain, the records are gone.\nLike a tooth pulled from a full row, the wound unnervingly smooth.") },
    { t: L("这手法,你认得。\n“天才俱乐部”在整部历史里无痕无迹——用的,就是这一种抹除。",
        "You know this technique.\nIt is exactly how the “Genius Club” left not one trace in all of recorded history — the very same erasure.") },
    { grant: "d06" },
    { back: true },
  ],

  /* ═══ 蓝鸟酒吧 ═══ */
  bar_listen: [
    { art: "🍺" },
    { t: L("你端着一杯假装在喝的啤酒,竖起耳朵。\n卡座里,大脸猫正给小弟们画饼:“干完这票,每人一栋楼!”",
        "You nurse a beer you're only pretending to drink, ears wide open.\nIn the booth, Bigface is selling his crew the dream: “After this job — a building for every one of you!”") },
    { t: L("过了一会儿,他去洗手间。你跟进去,借着隔间的死角,听见他对着镜子低声练习:\n“这人手脚不干净,留不得。”“这人勾引你嫂子,留不得。”……\n他把每一个小弟的“死法台词”,都排练好了。",
        "A while later he heads for the restroom. You follow, and from the blind corner of a stall you hear him rehearsing to the mirror:\n“This one had sticky fingers — can't keep him.” “This one flirted with your sister-in-law — can't keep him.”…\nHe has scripted a death line for every single member of his crew.") },
    { grant: "c03" },
    { back: true },
  ],
  bar_talk: [
    { art: "🎭" },
    { t: L("你在他对面坐下,不等他发作,先开口:\n“放风的、剪警报的、切电路的——你打算一个一个全干掉。台词我都会背:手脚不干净,留不得。”",
        "You sit down across from him and speak before he can bristle:\n“The lookout, the wire man, the electrician — you plan to drop them all, one by one. I know the lines by heart: sticky fingers, can't keep him.”") },
    { t: L("大脸猫的手僵在酒杯上。面具后的眼睛眯成两条缝:“……你谁?”",
        "Bigface's hand freezes on his glass. Behind the mask his eyes narrow to slits: “…Who are you?”") },
    { cond: (G) => hasPerk("p_confident"),
      t: L("你端起他的酒喝了一口,不紧不慢——这份从容是在现实里被赵总的气场熏出来的。\n“一个能帮你拿到那样东西的人。”",
        "You lift his drink and take an unhurried sip — a composure steeped, in reality, in Director Zhao's presence.\n“Someone who can get you that certain thing.”") },
    { t: L("沉默了很久,这个满脸横肉的男人忽然泄了气。\n“……我女儿。”他说,“他们害了我女儿。我查了很多年,只查到一个名字:天才俱乐部。”",
        "After a long silence, the burly man suddenly deflates.\n“…My daughter,” he says. “They destroyed my daughter. I've dug for years, and all I ever found was a name: the Genius Club.”") },
    { t: L("“钱不重要。金库里有个保险柜,里面据说锁着一张请柬——只有最顶级的天才和大人物才收得到的请柬。\n有了它,我才能找到那群人。”",
        "“The money means nothing. There's a safe in that vault, and inside it — they say — an invitation. The kind only the greatest geniuses and the most powerful ever receive.\nWith it, I can finally find those people.”") },
    { grant: "c04" },
    { grant: "c10" },
    { back: true },
  ],
  bar_persuade: [
    { art: "🤝" },
    { t: L("“我有办法打开那个保险柜。”你把气割枪的原理摊开讲给他听,“3000℃,切豆腐一样。”",
        "“I know how to open that safe.” You lay out the torch, piece by piece. “Three thousand degrees. Cuts it like tofu.”") },
    { t: L("“但是两罐高压气体,几十米的管子,喷枪、护目镜——至少五六个人手。\n所以今晚,一个小弟都不许杀。团结,就是力量。”",
        "“But two pressurized tanks, meters of hose, the torch, the goggles — five or six pairs of hands, minimum.\nSo tonight, not one man of yours dies. Strength — in numbers.”") },
    { t: L("大脸猫捏着酒杯,横肉拧了半天,最后从牙缝里挤出一个字:\n“……好。”",
        "Bigface grips his glass, jaw working for a long moment, and finally squeezes one word through his teeth:\n“…Fine.”") },
    { set: (G) => { G.run.flags.gangAlly = true; } },
    { t: L("(今晚,大脸猫的团伙会保留完整人手。梦境每晚重置——这场说服,每晚都要重来。)",
        "(Tonight, Bigface's crew stays intact. The dream resets nightly — this persuasion must be redone each night.)") },
    { back: true },
  ],
  bar_father: [
    { art: "🍺" },
    { t: L("“脸哥,问你个私事。”你给他续上酒,“你父亲……是做什么的?”",
        "“Something personal, boss.” You top up his glass. “Your father… what does he do?”") },
    { t: L("大脸猫的手停在半空。很久,他闷下那杯酒:\n“老数学家。一辈子就琢磨一个东西,什么……宇宙常数。”",
        "Bigface's hand stops mid-air. After a long moment he downs the drink:\n“Old mathematician. Spent his whole life gnawing on one thing. Some… universal constant.”") },
    { who: L("大脸猫", "Bigface"), t: L("“算出来的那天,他疯了。见人就抓着人家胳膊,满头大汗地重复一句话。后来,新东海市来人了,客客气气,请他去讲学——学术论坛。”",
        "“The day he solved it, he went mad. Grabbed strangers by the arm, sweat pouring, repeating one sentence. Then people came from New Donghai City — all courtesy — invited him to lecture. An academic forum.”") },
    { who: L("大脸猫", "Bigface"), t: L("“从那以后,我再没见过他。”\n他捏着空杯子,横肉在颤,“我查了很多年。查到最后,只查到三个字——天才俱乐部。”",
        "“I never saw him again.”\nHe grips the empty glass, jowls trembling. “I dug for years. And at the bottom of it all, three words — the Genius Club.”") },
    { grant: "d03" },
    { t: L("(情报手册已更新老宅的位置。)", "(The journal has been updated with the old house's location.)") },
    { back: true },
  ],

  /* ═══ 天台 · CC ═══ */
  cc_talk: [
    { art: "🌃" },
    { cond: (G) => (G.meta.ms.ccTalks || 0) >= 2, goto: "cc3" },
    { cond: (G) => (G.meta.ms.ccTalks || 0) >= 1, goto: "cc2" },
    { t: L("23:30。通风口的格栅无声滑开,一个黑影翻了出来——正要俯身入管,僵住了。\n你就坐在管道口,朝她挥挥手:“辛苦。走这条路的,除了你没别人吧?”",
        "23:30. The vent grille slides open in silence; a shadow swings out — and freezes mid-crouch.\nYou're sitting right at the duct mouth. You wave. “Long night. Nobody else uses this route, do they?”") },
    { who: "CC", t: "…………" },
    { t: L("枪口抬起,又缓缓放下。面具后传来一声极轻的、像认命一样的叹息:\n“林弦。你到底想干什么?”",
        "The muzzle rises, then slowly lowers. From behind the mask, the faintest sigh — like resignation itself:\n“Lin Xian. What is it you want?”") },
    { t: L("——她知道你的名字。\n你分明是第一次“认识”她,而她看你的眼神,像看一个认识了很久很久的人。",
        "— She knows your name.\nYou are, by any measure, strangers. Yet she looks at you the way one looks at someone known for a very, very long time.") },
    { grant: "c11" },
    { set: (G) => { G.meta.ms.ccTalks = 1; SAVE.save(G.meta); } },
    { back: true },

    { label: "cc2" },
    { t: L("她又一次在通风口撞见你。这一次,她连枪都懒得抬了。\n“你还想干什么?”",
        "Once again she finds you at the vent. This time she doesn't even bother raising the gun.\n“What now?”") },
    { menu: [
      { text: L("告诉她:“今年是2624年,而我来自六百年前。”", "Tell her: “This is the year 2624 — and I come from six hundred years ago.”"), req: ["c09"], goto: "cc2y" },
      { text: L("只是闲聊两句", "Just make small talk"), goto: "cc2n" },
    ]},
    { label: "cc2y" },
    { t: L("面具后的呼吸,停了一拍。\n她没有笑你疯,也没有反驳。很久,她说:“……那只保险柜,我找了七年。密码不是我的任何纪念日。”",
        "Behind the mask, her breath skips once.\nShe doesn't laugh, doesn't argue. At last she says: “…That safe. I've hunted it for seven years. The code is none of my anniversaries.”") },
    { t: L("“上面刻着的名字,和你一模一样。”\n风把她的下一句话吹散了。你只看清面具下微微绷紧的下颌线。",
        "“The name engraved on it is exactly yours.”\nThe wind scatters whatever she says next. All you catch is the faint tightening of her jaw beneath the mask.") },
    { set: (G) => { G.meta.ms.ccTalks = 2; SAVE.save(G.meta); } },
    { back: true },
    { label: "cc2n" },
    { t: L("你们有一搭没一搭地聊天。她的话很少,但没有赶你走。\n(似乎需要一个足够震撼的话题,才能敲开她的心防。)",
        "You chat about nothing much. She says little, but she doesn't send you away.\n(It seems only a truly staggering topic will crack her guard.)") },
    { back: true },

    { label: "cc3" },
    { t: L("“我有一个计划。”你盘腿坐下,拍拍身边的水泥台,“气割枪,五六个人,把那只箱子切开。你、我、大脸猫,还有他那几个命不该绝的小弟。”",
        "“I have a plan.” You sit cross-legged and pat the concrete beside you. “A cutting torch, five or six people, and we open that box. You, me, Bigface — and those crew members of his who don't deserve to die.”") },
    { who: "CC", t: L("……和劫匪合作?你疯了。", "…Team up with robbers? You're insane.") },
    { t: L("“梦里疯一点怎么了。”你说,“反正到了00:42,一切重来。只有答案能留下。”",
        "“What's a little insanity, in a dream?” you say. “At 00:42 it all resets anyway. Only the answers get to stay.”") },
    { t: L("面具后沉默了很久很久。然后,你第一次听见她笑了一声——很轻,像冰面裂开一道缝。\n“好。算我一个。”",
        "A long, long silence behind the mask. Then, for the first time, you hear her laugh — softly, like a crack opening across ice.\n“Fine. Count me in.”") },
    { set: (G) => { G.meta.ms.ccTalks = 3; SAVE.save(G.meta); } },
    { t: L("(合作路线已就绪:今晚在酒吧说服大脸猫留下人手,再于23:00后潜入金库,选择“上气割枪”。)",
        "(The cooperation route is ready: persuade Bigface at the bar to spare his crew tonight, then enter the vault after 23:00 and choose “bring up the torch.”)") },
    { back: true },
  ],
  cc_vv: [
    { art: "🌃" },
    { t: L("23:30,格栅准时滑开。她落地,看到你,已经懒得叹气了。\n“又来?这次想问什……”",
        "23:30. The grille slides open on schedule. She lands, sees you, and can't even muster a sigh.\n“Again? What is it this ti—”") },
    { t: L("“VV。”\n你只说了两个字母。", "“VV.”\nYou say only the two letters.") },
    { t: L("风声里,世界静了三秒。\n她的手扣在了枪柄上——不是杀意,是失控。面具后的呼吸乱得像溺水的人。",
        "In the wind, the world goes silent for three seconds.\nHer hand locks onto the pistol grip — not intent to kill, but loss of control. Behind the mask her breathing is that of someone drowning.") },
    { who: "CC", t: L("“……你从哪里,听到这个名字。”", "“…Where did you hear that name.”") },
    { t: L("你把照片递过去。她接照片的手,在抖。\n很久很久,她把照片还给你,声音哑得不像她:\n“问吧。今晚,你问什么我都答。”",
        "You hand her the photograph. Her hands shake as she takes it.\nA long, long while later she gives it back, her voice a rasp that doesn't sound like her at all:\n“Ask. Tonight, I'll answer anything.”") },
    { menu: [
      { text: L("“带我进新东海市。”", "“Take me into New Donghai City.”"), goto: "vv_deal" },
    ]},
    { label: "vv_deal" },
    { who: "CC", t: L("“……你知道我为什么走通风管、蒙着脸吗?我是新东海市的通缉客。”",
        "“…Do you know why I travel by air duct, why I mask my face? I am wanted in New Donghai City.”") },
    { who: "CC", t: L("“但也正因为这样——我知道一条内部人才用的密道。下水道,西三支线,尽头有一扇没有编号的门。”",
        "“But for exactly that reason — I know a passage only insiders use. The sewers. West branch three. At its end, a door with no number.”") },
    { t: L("她转身走向天台边缘,夜风掀起她的衣角。\n“备齐了就来找我。我带你进去——去看看那个把‘VV’锁进保险箱的世界,到底想干什么。”",
        "She turns toward the roof's edge, night wind lifting the hem of her coat.\n“Come find me when you're ready. I'll take you in — to see what the world that locked ‘VV’ inside a safe is really after.”") },
    { grant: "d08" },
    { set: (G) => { G.meta.ms.ccTalks = Math.max(G.meta.ms.ccTalks || 0, 1); SAVE.save(G.meta); } },
    { back: true },
  ],

  /* ═══ 广场 · 钟楼 ═══ */
  plaza_clock: [
    { art: "🕐" },
    { t: L("钟楼的巨钟一丝不苟地走着。22:00、23:00、00:00……然后,永远停在00:42。\n这座城市所有的钟,都活不过那一刻。",
        "The great clock keeps immaculate time. 22:00, 23:00, 00:00… and then, forever, it stops at 00:42.\nNo clock in this city outlives that minute.") },
    { back: true },
  ],
  plaza_sewer: [
    { art: "🕳️" },
    { t: L("后巷的下水道井盖虚掩着。你捏着鼻子下去,发现里面干燥得意外,通道笔直,四通八达。",
        "The manhole in the back alley sits ajar. You climb down, nose pinched — and find it surprisingly dry, the tunnels straight and branching everywhere.") },
    { t: L("银行、图书馆、天街……每个出口都有褪色的路牌。\n这座城市的“地下高速”,以后去哪儿都只要五分钟。",
        "The bank, the library, Skystreet… every exit bears a faded signpost.\nThe city's own underground expressway — from now on, anywhere is five minutes away.") },
    { grant: "c14" },
    { back: true },
  ],
  plaza_doom: [
    { art: "🌆" },
    { t: L("你爬上观景台,找了个最好的位置坐下,像等一场烟花。",
        "You climb to the observation deck and take the best seat in the house, as if waiting for fireworks.") },
    { t: L("00:40。城市的灯光开始一片一片熄灭。\n00:41。天空卷起,像燃烧的胶片。远处的高楼无声地折断、悬浮、碎裂。",
        "00:40. The city's lights begin going out, district by district.\n00:41. The sky curls up like burning film. Distant towers snap, hang weightless, and shatter — all in silence.") },
    { t: L("00:42。\n毁灭的浪头涌到脚下的一瞬间,你看清了它的样子——不是爆炸,更像是……整个世界被“合上”了。\n像一本读完的书。",
        "00:42.\nIn the instant the wave of ending reaches your feet, you finally see it clearly — not an explosion. More as if… the entire world were being closed.\nLike a book, finished.") },
    { end: (G) => window.__midnight() },
  ],

  /* ═══ 第二章 ═══ */
  ch2_intro: [
    { art: "🌙" },
    { t: L("【第二章 · 新东海市】\n拿到请柬的那一夜之后,你在梦里做的第一件事,是回到金库。",
        "[Chapter 2 · New Donghai City]\nAfter the night you claimed the invitation, the first thing you do in the dream is return to the vault.") },
    { art: "✉️" },
    { t: L("同一组密码。咔哒。\n请柬还躺在原处——但这一次,你注意到了别的东西:箱底的衬板,有一角微微翘起。",
        "The same code. Click.\nThe invitation lies where it lay — but this time you notice something else: one corner of the base panel, ever so slightly lifted.") },
    { t: L("夹层里是一张老照片。\n长发、大胡子的中年男人,站在一面写满公式的白板前。照片背面,只有两个字母:\nVV。",
        "In the false bottom: an old photograph.\nA long-haired, bearded man stands before a whiteboard dense with formulas. On the back, just two letters:\nVV.") },
    { t: L("你把照片凑到应急灯下,心脏漏跳了一拍。\n这个男人的侧脸——像极了你自己。",
        "You hold the photo up to the emergency light, and your heart skips.\nThe man's profile — is unmistakably your own.") },
    { grant: "d07" },
    { t: L("而请柬的背面,不知何时浮出一行烫金小字,像是遇热显影的墨:\n「新东海市」。\n城东那座高墙环绕的城中之城。你在这个梦里晃荡了二十多年,从没进去过。",
        "And on the invitation's back, gilt letters have surfaced like heat-developed ink:\n“New Donghai City.”\nThe walled city-within-a-city in the east. Twenty-odd years wandering this dream, and you've never once been inside.") },
    { grant: "d01" },
    { menu: [
      { text: L("把照片塞回夹层,离开金库(-60分)", "Tuck the photo back and leave the vault (-60 min)"), cost: 60, back: true },
    ]},
  ],

  gate_watch: [
    { art: "🏙️" },
    { t: L("你蹲在街对面的天桥上,盯了半个小时。\n进出的车辆在哨卡前停稳,乘客下车,对着一台银色立柱睁大眼睛——虹膜识别。然后是请柬,验的是“持有人”,不是纸。",
        "You crouch on the footbridge across the street and watch for half an hour.\nVehicles halt at the checkpoint; passengers step out and stare wide-eyed into a silver pillar — iris scan. Then the invitation: they verify the holder, not the paper.") },
    { t: L("有个醉汉想从栏杆底下钻过去。四个白衣人无声地围上来,像捡一片落叶一样把他“请”了出来,放在街角,拍拍灰,走了。\n全程没有一句话。",
        "A drunk tries to wriggle under the railing. Four men in white close in without a sound, lift him out like a fallen leaf, set him on the corner, brush him off, and leave.\nNot one word, start to finish.") },
    { grant: "d02" },
    { back: true },
  ],
  gate_force: [
    { art: "🏙️" },
    { t: L("你深吸一口气,翻过栏杆,朝墙内狂奔——", "You take a deep breath, vault the railing, and sprint for the wall —") },
    { t: L("视野忽然倒转。你甚至没看清他们是怎么出手的。\n白衣人把你轻轻放在街角,像放一件易碎品。其中一个俯下身,隔着口罩,极轻地说了一句:",
        "The world flips. You never even see them move.\nThe men in white set you down on the corner, gently, like fragile freight. One bends close and, through his mask, says very softly:") },
    { who: L("白衣人", "Man in White"), t: L("“回去吧,林先生。还不到时候。”", "“Go home, Mr. Lin. It is not yet time.”") },
    { die: L("他们知道你的名字。这个认知比任何暴力都更让你窒息——意识,在震惊中沉了下去。",
        "They know your name. The realization suffocates worse than any violence — and your consciousness sinks under the shock.") },
  ],

  house_42: [
    { art: "🏚️" },
    { t: L("门没锁。灰尘在手电光柱里浮沉。\n你推开里屋的门——然后僵在原地。",
        "The door is unlocked. Dust drifts through your flashlight beam.\nYou push open the inner door — and freeze.") },
    { art: "🕮" },
    { t: L("墙上。天花板上。地板上。衣柜的门板上。\n密密麻麻,层层叠叠,全是同一个数字:\n42。",
        "On the walls. The ceiling. The floorboards. The wardrobe doors.\nDense, layered, everywhere — one number, over and over:\n42.") },
    { t: L("粉笔的、钢笔的、指甲刻的。有的工整,有的癫狂,越靠近书桌越深,像某种漩涡的中心。\n宇宙常数——等于42。",
        "In chalk, in pen, gouged by fingernails. Some neat, some deranged — denser toward the desk, like the eye of a whirlpool.\nThe universal constant — equals 42.") },
    { grant: "d04" },
    { back: true },
  ],
  house_desk: [
    { art: "🏚️" },
    { t: L("书桌上摆着老花镜、凉透的茶、卷了边的演算纸镇——唯独没有纸。\n一张都没有。",
        "On the desk: reading glasses, tea gone stone-cold, a curling paperweight for manuscripts — and no paper.\nNot a single sheet.") },
    { t: L("抽屉空的。废纸篓空的。连墙上那些42的间隙里,原本贴着手稿的图钉,都只剩下钉孔。\n《宇宙常数导论》和它的一切,像被人从世界上整页撕走了。",
        "Drawers empty. Wastebasket empty. Even between the 42s on the walls, where manuscripts once hung, only pinholes remain.\nAn Introduction to the Universal Constant — and everything of it — torn from the world, page and all.") },
    { t: L("不是搬走。是抹除。\n这种“干净”,你在哪儿见过——",
        "Not moved out. Erased.\nAnd this particular kind of “clean” — you have seen it somewhere before—") },
    { grant: "d05" },
    { back: true },
  ],

  sneak: [
    { art: "🕳️" },
    { t: L("西三支线。CC在前面带路,手电的光斑贴着湿滑的管壁移动。\n尽头,一扇没有编号的铁门。她按了七下,门开了。",
        "West branch three. CC leads the way, her flashlight spot sliding along the slick tunnel wall.\nAt the end: an iron door with no number. She presses seven times. It opens.") },
    { cond: (G) => G.run.flags.gangAlly, goto: "sneak_pick" },
    { goto: "x1" },

    { label: "sneak_pick" },
    { menu: [
      { text: L("就我们两个,轻装潜入", "Just the two of us — go in light"), goto: "x1" },
      { text: L("叫上大脸猫——他父亲就在里面", "Bring Bigface — his father is in there"), goto: "x2" },
    ], prompt: L("门后,是另一个世界。带谁进去?", "Beyond this door lies another world. Who comes with you?") },

    { label: "x1" },
    { art: "🏙️" },
    { t: L("墙内的新东海市,安静得像一座实验室。\n街道一尘不染,路灯的光是冷白色的,每一栋楼都在最恰当的位置——恰当得,不像人住的地方。",
        "Inside the wall, New Donghai City is quiet as a laboratory.\nStreets spotless, lamplight a cold white, every building in exactly the right place — so right, it doesn't feel like anywhere people live.") },
    { t: L("CC领着你贴墙前行,停在一栋亮灯的大楼外。\n铭牌:学术交流中心。今天,是论坛的日子。",
        "CC leads you along the walls and stops outside a lit building.\nThe plaque: Academic Exchange Center. Today is the day of the forum.") },
    { t: L("透过巨大的落地窗,你看见了里面的会议室——\n白板上,写满了42。\n和老宅的墙,一模一样。",
        "Through the vast floor-to-ceiling window you see the conference room —\nwhiteboards covered in 42s.\nExactly like the walls of the old house.") },
    { t: L("白板前站着一个背对着你的男人。长发,披肩。\n他在讲话。声音透过玻璃传来,很模糊——\n但你还是听清了。",
        "Before the whiteboards stands a man with his back to you. Long hair, past his shoulders.\nHe is speaking. Through the glass the voice is muffled —\nbut you make it out all the same.") },
    { t: L("因为那个声音,\n和你的,一模一样。", "Because that voice\nis exactly, precisely, your own.") },
    { set: (G) => { G.meta.ms.sneakSolo = true; SAVE.save(G.meta); } },
    { t: L("“走!巡逻要过来了!”CC拽着你缩回阴影。\n远处,天边泛起熟悉的白光。00:42,不会为任何人停留。",
        "“Move! Patrol incoming!” CC yanks you back into shadow.\nFar off, the familiar white glow climbs the horizon. 00:42 waits for no one.") },
    { end: (G) => window.__midnight() },

    { label: "x2" },
    { art: "🏙️" },
    { t: L("“我爸……真的在里面?”\n大脸猫的声音在发抖。这个敢拿枪顶着银行金库的男人,手心全是汗。",
        "“My dad… he's really in there?”\nBigface's voice is shaking. The man who'd put a gun to a bank vault has palms slick with sweat.") },
    { t: L("CC领着你们绕开巡逻,停在“学术交流中心”后侧的一扇矮窗外。\n窗内是一间起居室。白板,42,还有——一个伏在桌上写字的老人。",
        "CC steers you both around the patrols to a low window at the rear of the Academic Exchange Center.\nInside: a living room. Whiteboards. 42s. And — an old man hunched over a desk, writing.") },
    { t: L("大脸猫扒住窗沿的手,青筋暴起。\n“爸。”他隔着玻璃,极轻地喊了一声。",
        "Bigface grips the sill, veins standing out on his hands.\n“Dad.” He calls it through the glass, barely above a breath.") },
    { t: L("老人抬起头。浑浊的眼睛对上儿子的,忽然清明了一瞬。\n他扑到窗边,抓住儿子扒着窗沿的手指,只重复一句话:",
        "The old man looks up. His clouded eyes meet his son's — and for one instant, they clear.\nHe lunges to the window, seizes his son's fingers on the sill, and repeats one sentence, over and over:") },
    { who: L("猫爸", "The Old Man"), t: L("“42……不要算42……谁都不要,再算出42……”",
        "“42… don't solve 42… no one must ever… solve 42 again…”") },
    { t: L("警报声起。CC几乎是拖着两个人撤进下水道的。\n黑暗里,你听见身后那个满手血腥的悍匪,哭得像个孩子。",
        "Alarms rise. CC all but drags the two of you back into the sewers.\nIn the dark behind you, the blood-soaked bandit is crying like a child.") },
    { set: (G) => { G.meta.ms.fatherSon = true; SAVE.save(G.meta); } },
    { end: (G) => window.__midnight() },
  ],

  /* ═══ 第二章 · 现实幕 ═══ */
  a1: [
    { art: "🏥" },
    { t: L("【现实 · 公司讲座】\n人事部组织了一场心理健康讲座。主讲教授带来一个实习生——心理系的学妹,楚安晴。",
        "[Reality · Company Lecture]\nHR organizes a mental-health lecture. The professor brings along an intern — a psychology student named Chu Anqing.") },
    { t: L("她走上台,开口的第一句话,你手里的笔就掉了。\n那个声音。你在梦里的天台上,听过几十遍。",
        "She steps up to the podium, and at her first sentence the pen drops from your hand.\nThat voice. You have heard it dozens of times — on a rooftop, in a dream.") },
    { t: L("讲座结束,她收拾资料时朝你看了一眼,礼貌地笑了笑——是陌生人的笑。\n可你盯着她的侧脸,满脑子都是那只白色面具。\n六百年。这中间隔着六百年。为什么会像?",
        "After the lecture she glances over while gathering her notes and smiles politely — a stranger's smile.\nBut you stare at her profile and see nothing but a white mask.\nSix hundred years. Six hundred years lie between them. Why the resemblance?") },
    { t: L("(那晚回家,你把和CC的每一次对话都记了下来。有些话术,现实里也许用得上。)",
        "(That night you write down every conversation you've ever had with CC. Some of those techniques may serve in reality too.)") },
    { end: (G) => finishReality("p_insight") },
  ],
  a2: [
    { art: "🏢" },
    { t: L("【现实 · 顶层办公室】\n“做我的兼职秘书吧。”赵英珺说得平静,“你会接触到一些……机密。”",
        "[Reality · Top-Floor Office]\n“Be my part-time secretary,” Zhao Yingjun says evenly. “You'll be handling certain… confidential matters.”") },
    { t: L("上任第一天,你替她归档文件,亲眼看着她把那张暗红色请柬,锁进顶层办公室的保险柜。\n输密码时,她的手指没有一丝犹豫。",
        "On your first day, filing her documents, you watch her lock the dark red invitation into the top-floor safe.\nHer fingers enter the code without a moment's hesitation.") },
    { t: L("锁上之后,她隔着柜门看了很久。那眼神不是好奇,也不是敬畏——\n更像是在看一个如约而至的旧物。\n她,到底知道多少?",
        "After it locks she stands looking at the door for a long time. Not curiosity. Not awe —\nmore like regarding an old possession that has arrived exactly on schedule.\nHow much, exactly, does she know?") },
    { grant: "d10" },
    { end: (G) => finishReality(null) },
  ],
  a3: [
    { art: "🪞" },
    { t: L("【现实 · 凌晨的洗手间】\n你把那张只存在于记忆里的照片,一笔一笔画了下来,贴在镜子边上。",
        "[Reality · Bathroom, Small Hours]\nStroke by stroke, you redraw the photograph that exists only in your memory, and tape it to the edge of the mirror.") },
    { t: L("长发。大胡子。你对着镜子,把头发抓乱,用手掌挡住下巴想象胡须——\n镜子里的人,和画上的人,慢慢重合。",
        "Long hair. Full beard. You muss your hair in the mirror, cup a palm over your chin to fake the beard —\nand the man in the glass slowly converges with the man in the drawing.") },
    { t: L("VV。\n如果那真的是六百年后的“你”……那他为什么在新东海市?为什么把照片留在刻着你名字的保险箱里?\n他是在,给你留路标吗?",
        "VV.\nIf that truly is “you,” six hundred years on… why is he in New Donghai City? Why leave a photograph inside a safe that bears your name?\nIs he leaving you — waypoints?") },
    { end: (G) => finishReality(null) },
  ],

  /* ═══ 现实幕 ═══ */
  r0: [
    { art: "🏢" },
    { t: L("【现实 · MX美妆公司】\n早高峰的地铁把你挤成相片,工位上的咖啡永远差三度。",
        "[Reality · MX Cosmetics]\nThe rush-hour subway presses you flat as a photograph; the coffee at your desk is forever three degrees too cold.") },
    { who: L("李主管", "Supervisor Li"), t: L("林弦!新品牌的形象设计,全组憋了两周一个能看的都没有!下周赵总亲自来评审,你们是想让我去跳江吗?!",
        "Lin Xian! Two weeks and this team hasn't produced one presentable brand design! Director Zhao reviews us in person next week — are you all trying to send me off a bridge?!") },
    { t: L("你打着哈欠点头称是。\n对别人来说,一天只有一天。而你的每个夜晚,还有另一个完整的世界。\n谁能想到呢——一个天天梦里“无法无天”的人,现实里是个连方案都憋不出的社畜。",
        "You nod along mid-yawn.\nFor everyone else, a day is just a day. But each of your nights holds an entire other world.\nWho would guess — the man who runs lawless through his dreams is, by daylight, a wage slave who can't squeeze out a single proposal.") },
    { end: (G) => finishReality(null) },
  ],
  r1: [
    { art: "🖊️" },
    { t: L("【现实 · 评审会】\n会议室鸦雀无声,赵总的脸色比冰还冷。你盯着草稿纸,忽然想起梦里那只猫。",
        "[Reality · The Review]\nThe meeting room is dead silent; Director Zhao's expression is colder than ice. Staring at your blank sheet, you suddenly think of the cat in the dream.") },
    { t: L("笔尖落纸,寥寥几行——耳朵、胡须、一条上翘的尾巴。那份活灵活现,是你在梦里看了不知多少遍的神态。",
        "The pen touches paper — a few spare lines. Ears, whiskers, one upturned tail. Its liveliness is an expression you have watched, countless times, in the dream.") },
    { t: L("邻座的同事先惊呼出声。然后是整个设计部。\n连赵英珺都拿起了那张纸,端详许久:“不错。它叫什么?”",
        "The colleague beside you gasps first. Then the whole design department.\nEven Zhao Yingjun picks up the sheet and studies it at length. “Not bad. What's its name?”") },
    { menu: [
      { text: L("“叫……莱茵。”", "“Call her… Rhein.”"), goto: "r1_name" },
    ]},
    { label: "r1_name" },
    { set: (G) => { G.meta.butterfly.cat = true; SAVE.save(G.meta); } },
    { t: L("“莱茵。”赵英珺点头,“新品牌形象,就用它。”\n散会后,全组看你的眼神都变了。你捏着那张草稿纸,忽然生出一个荒谬的念头:\n——如果梦是真的,我在现实里改变的东西,梦里会跟着变吗?",
        "“Rhein.” Zhao Yingjun nods. “That's our new brand image.”\nAfter the meeting, the whole team looks at you differently. Clutching the sketch, an absurd thought rises:\n— if the dream is real, will what I change in reality change there too?") },
    { end: (G) => finishReality("p_confident") },
  ],
  r2: [
    { art: "📕" },
    { t: L("【现实 · 深夜书房】\n你想起那个在洗手间对着镜子排练“处决台词”的男人,和他反复摩挲的一张旧照片。",
        "[Reality · Study, Late Night]\nYou think of the man rehearsing execution lines to a restroom mirror — and of the worn old photo he kept thumbing.") },
    { t: L("要撬开那样一个人的心防,靠的不是拳头。你下单了三本谈判与共情心理学,一夜读完两本。\n有些技巧,梦里马上就用得上。",
        "Cracking a man like that open takes no fists. You order three books on negotiation and empathy and finish two before dawn.\nSome of these techniques will be useful in the dream immediately.") },
    { end: (G) => finishReality("p_talk") },
  ],
  r3: [
    { art: "🔧" },
    { t: L("【现实 · 搜索引擎】\n“打不开的保险箱,怎么开?”\n答案出奇一致:氧乙炔气割枪。3000℃的切割焰,焰心温度远超钢铁熔点。",
        "[Reality · Search Engine]\n“How do you open a safe that won't open?”\nThe answers are strikingly unanimous: an oxy-acetylene torch. A 3000°C flame, its core far beyond the melting point of steel.") },
    { t: L("你看了一晚上的切割视频:白炽的火舌贴上箱体,钢板像豆腐一样卷开。\n问题只有一个——两罐高压气体沉得要命,至少需要五六个人。\n五六个人……你在梦里,上哪儿凑五六个信得过的人?",
        "You watch cutting videos all night: the white tongue of flame touches steel, and the plate curls away like tofu.\nOnly one problem — the pressurized tanks are brutally heavy. Five or six people, minimum.\nFive or six… and where, in the dream, do you find five or six people you can trust?") },
    { grant: "c16" },
    { end: (G) => finishReality(null) },
  ],
  r4: [
    { art: "🌀" },
    { t: L("【现实 · 凌晨】\n你搜遍了整个互联网:“2624”“预知梦”“重复梦境”……\n没有任何人,做过和你一样的梦。",
        "[Reality · Small Hours]\nYou scour the whole internet: “2624,” “precognitive dreams,” “recurring dreams”…\nNo one, anywhere, has ever dreamed what you dream.") },
    { t: L("00:41,你盯着天花板。00:42,窗外安然无恙。\n现实的世界不会毁灭——毁灭的只是那个“未来”。",
        "00:41 — you stare at the ceiling. 00:42 — outside the window, nothing.\nThe real world does not end. What ends is only that “future.”") },
    { t: L("既然答案都在梦里,那就别浪费现实的每一秒。\n你把作息表整个推翻:提前洗漱、提前躺下、提前入梦。从今晚起,每一夜,你都比过去多出十分钟。",
        "If every answer lives in the dream, then waste not one second of reality.\nYou tear up your whole routine: wash earlier, lie down earlier, dream earlier. From tonight, every night gives you ten more minutes than before.") },
    { end: (G) => finishReality("p_resolve") },
  ],
  r5: [
    { art: "✉️" },
    { t: L("【现实 · MX公司前台】\n你抱着莱茵猫的打样玩偶路过前台,前台小姐姐叫住你:“林弦,帮忙把这个带给赵总。”",
        "[Reality · MX Front Desk]\nCarrying a sample Rhein-cat plush past reception, you're flagged down: “Lin Xian — take this up to Director Zhao, would you?”") },
    { t: L("一张暗红色的卡片,烫金的四个字。\n天才俱乐部。", "A dark red card. Four gilt characters.\nThe Genius Club.") },
    { t: L("和梦里保险箱中的那张,一模一样。\n它不该存在于现实——这个名字你只在六百年后的梦里听过。可它就躺在你的掌心,墨香未散。",
        "Identical to the one inside the dream's safe.\nIt should not exist in reality — you've only ever heard the name six hundred years from now. Yet here it lies in your palm, the ink still fragrant.") },
    { t: L("走廊尽头,赵英珺接过请柬,正面看了看,背面看了看,表情没有一丝波澜,仿佛只是收到一张普通的会议通知。\n她的高跟鞋声消失在电梯里。",
        "At the corridor's end Zhao Yingjun takes the invitation, examines the front, then the back, her expression without a single ripple — as if receiving an ordinary meeting notice.\nThe sound of her heels vanishes into the elevator.") },
    { set: (G) => { G.meta.ms.r5 = true; SAVE.save(G.meta); } },
    { end: (G) => finishReality(null) },
  ],

  /* ═══ 结局场景(第二章) ═══ */
  ending_x1: [
    { art: "🏙️" },
    { t: L("醒来后,你在天花板上盯了整整一夜。", "Awake, you stare at the ceiling until dawn.") },
    { t: L("墙内的世界、写满42的白板、被“抹除”的书、以及那个声音——\n那个和你一模一样的声音。",
        "The world inside the wall. Whiteboards full of 42s. Books “erased” from existence. And that voice —\nthe voice identical to your own.") },
    { t: L("宇宙常数是什么?算出它的人为什么会疯?\n新东海市在保护什么,又在掩埋什么?\nVV……到底是不是六百年后的你?",
        "What is the universal constant? Why does solving it break a mind?\nWhat is New Donghai City protecting — and what is it burying?\nAnd VV… is he, or is he not, you — six hundred years from now?") },
    { t: L("谜团铺成了一张更深的网。但你已经站在网的中央。\n下一次入梦,你不再是访客了。\n你是回声,正在找到自己的源头。",
        "The riddles weave a deeper web. But you now stand at its center.\nNext time you dream, you will be no visitor.\nYou are an echo — closing in on its source.") },
    { end: (G) => endingCard("X1") },
  ],
  ending_x2: [
    { art: "🎭" },
    { t: L("那一夜之后,大脸猫变了。\n他不再擦枪,不再对着镜子练习狠话。他坐在蓝鸟酒吧的老位置,一遍一遍画着一扇矮窗。",
        "After that night, Bigface is changed.\nHe no longer cleans his gun, no longer rehearses cruelty into mirrors. He sits in his old booth at the Bluebird, drawing one low window, over and over.") },
    { who: L("大脸猫", "Bigface"), t: L("“老弟,我爸疯了,可他抓着我的手的时候……他认得我。”",
        "“Kid — my old man's gone mad. But when he grabbed my hand… he knew me.”") },
    { who: L("大脸猫", "Bigface"), t: L("“他说,谁都不要再算出42。你说,这话是疯话,还是——遗言?”",
        "“He said no one must ever solve 42 again. Tell me — is that madness, or is it… a last testament?”") },
    { t: L("你没有回答。\n因为你想起了老宅墙上那个漩涡的中心,想起了平整得吓人的抹除创口。\n有些数字,也许本来就不该被算出来。\n可是——已经有人算出来了。",
        "You don't answer.\nBecause you're thinking of the whirlpool's eye on the old house wall, and of erasure wounds cut unnervingly smooth.\nPerhaps some numbers were never meant to be solved.\nAnd yet — someone already has.") },
    { end: (G) => endingCard("X2") },
  ],

  /* ═══ 结局场景 ═══ */
  ending_e1: [
    { art: "💤" },
    { t: L("你不再追问保险箱,不再理会CC,不再管什么2624。\n梦里,你夜夜躺在金库的钱堆上;现实里,“莱茵猫之父”的头衔让你平步青云。",
        "You stop asking about the safe, stop minding CC, stop caring about 2624.\nIn the dream you sleep on vault money every night; in reality, the title “father of the Rhein cat” carries you ever upward.") },
    { t: L("只是偶尔,在00:41的钟声里,你会想起那只刻着你名字的箱子。\n它还在那里。它会一直在那里。\n每一夜,都在那里。",
        "Only sometimes, in the chime of 00:41, you remember the safe that bears your name.\nIt is still there. It will always be there.\nEvery night. There.") },
    { end: (G) => endingCard("E1") },
  ],
  ending_e2: [
    { art: "✉️" },
    { t: L("梦里的请柬,和现实里的请柬,在你脑海中重叠在一起。",
        "The invitation in the dream and the invitation in reality overlap, perfectly, in your mind.") },
    { t: L("一个只存在于六百年后的名字,为什么会出现在今天的现实?\n是谁,在六百年前就收到了“未来”的邀请?\n那只刻着「林弦」的保险箱,又是哪个“林弦”锁上的?",
        "Why does a name that exists only six hundred years from now appear in today's reality?\nWho received an invitation from the “future,” six centuries early?\nAnd that safe engraved Lin Xian — which Lin Xian locked it?") },
    { t: L("你站在公司楼下,抬头望着22层的灯光。\n谜团没有减少,反而张开了一张更大的网。\n——但至少,你终于摸到了网的边缘。",
        "You stand below the office tower, looking up at the lights of the 22nd floor.\nThe mysteries have not thinned; they have spread into a vaster web.\n— But at least, at last, your fingers have found its edge.") },
    { t: L("梦还会继续。00:42还会到来。\n而这一次,你不再是困在时间里的囚徒。\n你是唯一一个,同时活在两个时代的人。",
        "The dream will go on. 00:42 will come again.\nBut this time you are no prisoner of time.\nYou are the only person alive in two eras at once.") },
    { end: (G) => endingCard("E2") },
  ],
  ending_e3: [
    { art: "🎭" },
    { t: L("【CC视角】\n七年。她在这个通风管里爬进爬出了七年,枪口抵过无数人的额头,没有一次犹豫。",
        "[CC]\nSeven years. Seven years crawling in and out of this duct, her muzzle against countless foreheads, and never once a hesitation.") },
    { t: L("直到那个男人出现。知道她的路线,知道劫匪的台词,知道这个世界的年份——却把所有底牌摊开,只为凑齐“五六个人手”。",
        "Until that man appeared. Knowing her routes, knowing the robbers' scripts, knowing the very year of this world — and laying every card face-up, all to gather “five or six pairs of hands.”") },
    { t: L("金库里,火花温柔地落下。劫匪在哭,小弟们在分烟,那个男人靠着保险柜,笑得像是打赢了一场没人看见的战争。",
        "In the vault, sparks fall gently. The robber weeps, the crew shares cigarettes, and that man leans against the safe, smiling like the victor of a war no one else could see.") },
    { t: L("“喂。”摘下面具之前,她听见自己说,“下一夜,天台见。”\n反正,他一定会记得。\n——他什么都记得。",
        "“Hey.” Before removing her mask, she hears herself say: “Tomorrow night. The rooftop.”\nHe will remember. He always does.\n— He remembers everything.") },
    { end: (G) => endingCard("E3") },
  ],
};

/* ── 现实幕列表(第一个未播且已解锁的幕会被播放) ── */
const REALITY = [
  { scene: "r0", art: "🏢", unlock: (G) => true },
  { scene: "r1", art: "🖊️", unlock: (G) => hasClue("c15") },
  { scene: "r2", art: "📕", unlock: (G) => hasClue("c04") },
  { scene: "r3", art: "🔧", unlock: (G) => hasClue("c06") },
  { scene: "r4", art: "🌀", unlock: (G) => hasClue("c09") },
  { scene: "r5", art: "✉️", unlock: (G) => !!G.meta.ms.invite },
  /* —— 第二章 —— */
  { scene: "a1", art: "🏥", unlock: (G) => G.meta.chapter >= 2 },
  { scene: "a2", art: "🏢", unlock: (G) => G.meta.chapter >= 2 && hasClue("d06") },
  { scene: "a3", art: "🪞", unlock: (G) => G.meta.chapter >= 2 && hasClue("d08") },
];

/* ── 下一步提示(按主线链缺口,醒来结算卡上显示) ── */
function nextHint(G) {
  const has = (id) => G.meta.clues.includes(id);
  if (G.meta.chapter >= 2) {
    // 第二章提示链
    if (G.meta.endings.includes("X1") || G.meta.endings.includes("X2")) return null;
    if (!has("d08")) return L("天台上,把照片上的名字念给她听。", "On the rooftop, speak the name from the photograph to her.");
    if (!has("d03")) return L("酒吧里,问问他的父亲。", "At the bar, ask about his father.");
    if (!has("d04")) return L("去老宅看看——推开那扇门。", "Visit the old house — push open that door.");
    if (!has("d05")) return L("老宅的书桌上,本该有一本书。", "There should be a book on the old house's desk.");
    if (!has("d06")) return L("图书馆的馆藏记录,查得出“抹除”。", "The library's catalog can reveal the erasure.");
    if (!has("d09")) return L("再买一份今天的报纸。", "Buy today's paper once more.");
    return L("万事俱备。去新东海市关卡,走密道。", "All is ready. Head to the New Donghai checkpoint and take the hidden passage.");
  }
  if (G.meta.ms.invite) return null; // 主线已通
  if (!has("c01")) return L("再去经历一次那场劫案吧。", "Go live through that heist once more.");
  if (!has("c02")) return L("23:00 之前,银行大厅值得一逛。", "Before 23:00, the bank lobby is worth a stroll.");
  if (!has("c06")) return L("23:00 之后,跟着劫案走到最深处。", "After 23:00, follow the heist all the way down.");
  if (!has("c07")) return L("梦里的报纸,你仔细读过吗?", "Have you ever truly read the dream's newspaper?");
  if (!has("c08")) return L("旧书店,查得到很久以前的事。", "The old bookstore keeps the very distant past.");
  if (!has("c09")) return L("图书馆的后窗,还开着。", "The library's rear window is still open.");
  if (!has("c11")) return L("23:30 的天台,有人从通风管里出来。", "At 23:30 on the rooftop, someone climbs out of the duct.");
  if (!has("c12")) return L("回到保险箱前——密码,你已经可以推理出来了。", "Return to the safe — you can deduce the code now.");
  return L("带着密码,回到保险箱前。", "Take the code back to the safe.");
}

/* ── 结局(顺序即优先级) ── */
const ENDINGS = [
  /* 第二章 · 章节结局 */
  { id: "X2", title: L("父与子", "Father and Son"), scene: "ending_x2", art: "🎭",
    cond: (G) => G.meta.chapter >= 2 && !!G.meta.ms.fatherSon,
    chapterEnd: L("第二章 · 完\n第三章 · 敬请期待", "End of Chapter 2\nChapter 3 · Coming soon"),
    epitaph: L("高墙锁得住一个人,锁不住一声“爸”。", "A wall can hold a man. It cannot hold the word “Dad.”") },
  { id: "X1", title: L("城中之城", "The City Within"), scene: "ending_x1", art: "🏙️",
    cond: (G) => G.meta.chapter >= 2 && !!G.meta.ms.sneakSolo,
    chapterEnd: L("第二章 · 完\n第三章 · 敬请期待", "End of Chapter 2\nChapter 3 · Coming soon"),
    epitaph: L("墙内的声音,和你一模一样。", "The voice within the wall is exactly your own.") },
  /* 第一章 · 章节结局 */
  { id: "E3", title: L("同行者", "Fellow Travelers"), scene: "ending_e3", art: "🎭",
    cond: (G) => !!G.meta.ms.coopOpen,
    next: 2, chapterEnd: L("第一章 · 完", "End of Chapter 1"),
    epitaph: L("有些答案,一个人永远打不开。", "Some answers can never be opened alone.") },
  { id: "E2", title: L("二六二四", "Twenty Six Twenty Four"), scene: "ending_e2", art: "✉️",
    cond: (G) => !!G.meta.ms.invite && !!G.meta.ms.r5,
    next: 2, chapterEnd: L("第一章 · 完", "End of Chapter 1"),
    epitaph: L("梦是六百年后的未来。而未来,寄来了请柬。", "The dream is the future, six hundred years on. And the future has sent an invitation.") },
  /* 坏结局(可继续) */
  { id: "E1", title: L("循环囚徒", "Prisoner of the Loop"), scene: "ending_e1", art: "💤",
    cond: (G) => !!G.meta.ms.slacker && !G.meta.ms.invite && !G.meta.ms.coopOpen,
    epitaph: L("把无限当作躺平的理由,就永远只能重复这一天。", "Treat infinity as an excuse to coast, and this one day is all you will ever have.") },
];
